export const IMAGES = {
  hero: "https://images.unsplash.com/photo-1750405704388-1416715c359c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxIaW5kdSUyMHRlbXBsZSUyMEluZGlhJTIwZ29sZGVufGVufDF8fHx8MTc3MjEyNjA2NHww&ixlib=rb-4.1.0&q=80&w=1080",
  varanasi: "https://images.unsplash.com/photo-1741485332074-fa55a9c68fda?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxWYXJhbmFzaSUyMGdoYXQlMjBzdW5yaXNlfGVufDF8fHx8MTc3MjEyNjA2NXww&ixlib=rb-4.1.0&q=80&w=1080",
  kedarnath: "https://res.cloudinary.com/dikn5wjzs/image/upload/v1779204380/pexels-abhra-ghosh-362148807-16152405_hy6bdb.jpg",
  vrindavan: "https://images.unsplash.com/photo-1723741799382-363a277a05d4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxWcmluZGF2YW4lMjB0ZW1wbGUlMjBLcmlzaG5hfGVufDF8fHx8MTc3MjEyNjA2NXww&ixlib=rb-4.1.0&q=80&w=1080",
  tirupati: "https://images.unsplash.com/photo-1701309171892-ddd6161fb004?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxUaXJ1cGF0aSUyMEJhbGFqaSUyMHRlbXBsZXxlbnwxfHx8fDE3NzIxMjYwNjV8MA&ixlib=rb-4.1.0&q=80&w=1080",
  dwarka: "https://images.unsplash.com/photo-1717326630799-703fe906e283?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxEd2Fya2ElMjB0ZW1wbGUlMjBHdWphcmF0fGVufDF8fHx8MTc3MjEyNjA2Nnww&ixlib=rb-4.1.0&q=80&w=1080",
  pilgrims: "https://images.unsplash.com/photo-1758811402999-3551dd15d357?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxIaW5kdSUyMHBpbGdyaW1zJTIwaG9seSUyMHJpdmVyfGVufDF8fHx8MTc3MjEyNjA2N3ww&ixlib=rb-4.1.0&q=80&w=1080",
  architecture: "https://images.unsplash.com/photo-1759990251993-3e350f67cd31?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRpYW4lMjB0ZW1wbGUlMjBhcmNoaXRlY3R1cmUlMjBvcm5hdGV8ZW58MXx8fHwxNzcyMTI2MDY3fDA&ixlib=rb-4.1.0&q=80&w=1080",
  aarti: "https://images.unsplash.com/photo-1766344599202-233ef34a3482?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxIaW5kdSUyMHByYXllciUyMGNlcmVtb255JTIwYWFydGl8ZW58MXx8fHwxNzcyMTI2MDY4fDA&ixlib=rb-4.1.0&q=80&w=1080",
  mathura: "https://images.unsplash.com/photo-1703233491579-5a32609206a0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxNYXRodXJhJTIwdGVtcGxlJTIwYW5jaWVudHxlbnwxfHx8fDE3NzIxMjYwNjh8MA&ixlib=rb-4.1.0&q=80&w=1080",
  meditation: "https://images.unsplash.com/photo-1763336342966-51e84b8f052f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzcGlyaXR1YWwlMjBtZWRpdGF0aW9uJTIwdGVtcGxlJTIwcGVhY2VmdWx8ZW58MXx8fHwxNzcyMTI2MDY5fDA&ixlib=rb-4.1.0&q=80&w=1080",
  himalaya: "https://images.unsplash.com/photo-1767763713180-4ecf77279861?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxIaW1hbGF5YSUyMG1vdW50YWluJTIwc25vdyUyMHBpbGdyaW1hZ2V8ZW58MXx8fHwxNzcyMTI2MDcyfDA&ixlib=rb-4.1.0&q=80&w=1080",
  festival: "https://images.unsplash.com/photo-1761810255396-a52187ceec8d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxIaW5kdSUyMGRldm90ZWVzJTIwZmVzdGl2YWwlMjBjZWxlYnJhdGlvbnxlbnwxfHx8fDE3NzIxMjYwNzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  ganges: "https://images.unsplash.com/photo-1762006222577-0d44ab596183?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzYWNyZWQlMjByaXZlciUyMEdhbmdlcyUyMGNlcmVtb255fGVufDF8fHx8MTc3MjEyNjA3M3ww&ixlib=rb-4.1.0&q=80&w=1080",
};

export interface TourPackage {
  id: string;
  nameEn: string;
  nameHi: string;
  descEn: string;
  descHi: string;
  duration: string;
  durationHi: string;
  price: string;
  datesEn: string;
  datesHi: string;
  image: string;
  highlights: { en: string; hi: string }[];
  itinerary: { dayEn: string; dayHi: string; titleEn: string; titleHi: string; descEn: string; descHi: string }[];
  includes: { en: string; hi: string }[];
  excludes: { en: string; hi: string }[];
}

export const tourPackages: TourPackage[] = [
  {
    id: "char-dham",
    nameEn: "Char Dham Yatra 2026",
    nameHi: "चार धाम यात्रा 2026",
    descEn: "Sri Madanmohan Tirth Yatra, Jaipur presents Char Dham 2026 with two batches (30 Apr–13 May or 28 May–10 Jun). AC 27-seater bus from Jaipur, AC rooms in Haridwar, Kedarnath & Badrinath stays, satvik meals without onion/garlic, and guided darshan across all four dhams.",
    descHi: "श्री मदनमोहन तीर्थ यात्रा, जयपुर द्वारा चार धाम 2026 (दो बैच: 30 अप्रैल–13 मई या 28 मई–10 जून)। जयपुर से एसी 27 सीटर बस, हरिद्वार में एसी कमरे, केदारनाथ और बद्रीनाथ में ठहराव, बिना प्याज-लहसुन के सत्स्वादी भोजन और चारों धामों का मार्गदर्शित दर्शन।",
    duration: "14 Days / 13 Nights",
    durationHi: "14 दिन / 13 रातें",
    price: "₹27,000",
    datesEn: "Batch 1: 30 Apr – 13 May 2026\nBatch 2: 28 May – 10 Jun 2026",
    datesHi: "बैच 1: 30 अप्रैल – 13 मई 2026\nबैच 2: 28 मई – 10 जून 2026",
    image: IMAGES.kedarnath,
    highlights: [
      { en: "AC 27-seater bus from Jaipur (round trip)", hi: "जयपुर से एसी 27 सीटर बस (आना-जाना)" },
      { en: "Booking ₹2,000 non-refundable", hi: "बुकिंग ₹2,000 नॉन-रिफंडेबल" },
      { en: "Darshan: Shukratal, Lakshagrah, Shiv Gufa, Haridwar, Yamunotri, Gangotri, Kedarnath, Badrinath", hi: "दर्शन: शुक्रताल, लाक्षागृह, शिव गुफा, हरिद्वार, यमुनोत्री, गंगोत्री, केदारनाथ, बद्रीनाथ" },
    ],
    itinerary: [
      { dayEn: "Day 1", dayHi: "दिन 1", titleEn: "Jaipur to Haridwar (9:00 PM bus)", titleHi: "जयपुर से हरिद्वार (रात 9:00 बस)", descEn: "Departure 30 Apr 9:00 PM from Jaipur by AC 27-seater bus towards Haridwar.", descHi: "30 अप्रैल रात 9:00 बजे जयपुर से एसी 27 सीटर बस द्वारा हरिद्वार के लिए प्रस्थान।" },
      { dayEn: "Day 2", dayHi: "दिन 2", titleEn: "Haridwar stay & Ganga snan", titleHi: "हरिद्वार ठहराव और गंगा स्नान", descEn: "01 May: Check-in AC rooms Haridwar. Ganga snan and Har Ki Pauri aarti.", descHi: "01 मई: हरिद्वार में एसी कमरों में ठहराव। गंगा स्नान और हर की पौड़ी आरती।" },
      { dayEn: "Day 3", dayHi: "दिन 3", titleEn: "Haridwar to Barkot via Lakhamandal", titleHi: "हरिद्वार से बड़कोट (लाक्षागृह)", descEn: "02 May: Travel to Barkot; Lakhamandal/Lakshagrah darshan en route. Stay in Barkot.", descHi: "02 मई: बड़कोट प्रस्थान; मार्ग में लाक्षागृह/लखामंडल दर्शन। बड़कोट में ठहराव।" },
      { dayEn: "Day 4", dayHi: "दिन 4", titleEn: "Yamunotri darshan", titleHi: "यमुनोत्री दर्शन", descEn: "03 May: Yamunotri trek/doli/horse as needed; darshan and return to Barkot stay.", descHi: "03 मई: यमुनोत्री ट्रेक/डोली/घोड़ा आवश्यकता अनुसार; दर्शन कर बड़कोट वापसी।" },
      { dayEn: "Day 5", dayHi: "दिन 5", titleEn: "Barkot to Uttarkashi (Shiv Gufa)", titleHi: "बड़कोट से उत्तरकाशी (शिव गुफा)", descEn: "04 May: Move to Uttarkashi; Shiv Gufa darshan. Night stay Uttarkashi.", descHi: "04 मई: उत्तरकाशी प्रस्थान; शिव गुफा दर्शन। रात्रि विश्राम उत्तरकाशी।" },
      { dayEn: "Day 6", dayHi: "दिन 6", titleEn: "Gangotri darshan", titleHi: "गंगोत्री दर्शन", descEn: "05 May: Visit Gangotri temple, holy dip at Bhagirathi. Return Uttarkashi stay.", descHi: "05 मई: गंगोत्री मंदिर दर्शन, भागीरथी में पवित्र स्नान। उत्तरकाशी में ठहराव।" },
      { dayEn: "Day 7", dayHi: "दिन 7", titleEn: "Uttarkashi to Narayan Koti", titleHi: "उत्तरकाशी से नारायण कोटी", descEn: "06 May: Travel towards Kedarnath side; stay at Narayan Koti.", descHi: "06 मई: केदारनाथ मार्ग में यात्रा; नारायण कोटी में ठहराव।" },
      { dayEn: "Day 8", dayHi: "दिन 8", titleEn: "Kedarnath darshan (hill stay)", titleHi: "केदारनाथ दर्शन (पहाड़ी ठहराव)", descEn: "07 May: Kedarnath trek/pony/heli as arranged; evening stay near Kedarnath hill.", descHi: "07 मई: केदारनाथ ट्रेक/पोनी/हेली व्यवस्था अनुसार; शाम का ठहराव केदारनाथ पहाड़ी पर।" },
      { dayEn: "Day 9", dayHi: "दिन 9", titleEn: "Return to Narayan Koti", titleHi: "नारायण कोटी वापसी", descEn: "08 May: Descend from Kedarnath hill; overnight at Narayan Koti.", descHi: "08 मई: केदारनाथ पहाड़ी से उतरकर नारायण कोटी में रात्रि विश्राम।" },
      { dayEn: "Day 10", dayHi: "दिन 10", titleEn: "Narayan Koti to Badrinath", titleHi: "नारायण कोटी से बद्रीनाथ", descEn: "09 May: Travel to Badrinath; temple darshan and stay in Badrinath.", descHi: "09 मई: बद्रीनाथ प्रस्थान; मंदिर दर्शन और बद्रीनाथ में ठहराव।" },
      { dayEn: "Day 11", dayHi: "दिन 11", titleEn: "Badrivishal, Mana, Vyas Gufa", titleHi: "बद्रीविशाल, माणा, व्यास गुफा", descEn: "10 May: Badrivishal darshan, Mana village visit, Vyas Gufa, Tapt Kund. Night stay Badrinath.", descHi: "10 मई: बद्रीविशाल दर्शन, माणा गाँव, व्यास गुफा, तप्त कुंड। रात्रि विश्राम बद्रीनाथ।" },
      { dayEn: "Day 12", dayHi: "दिन 12", titleEn: "Badrinath to Haridwar", titleHi: "बद्रीनाथ से हरिद्वार", descEn: "11 May: Return towards Haridwar; night stay Haridwar.", descHi: "11 मई: हरिद्वार की ओर वापसी; रात्रि विश्राम हरिद्वार।" },
      { dayEn: "Day 13", dayHi: "दिन 13", titleEn: "Haridwar snan, Shukratal, return", titleHi: "हरिद्वार स्नान, शुक्रताल, वापसी", descEn: "12 May: Ganga snan at Har Ki Pauri, Shukratal darshan; depart for Jaipur.", descHi: "12 मई: हर की पौड़ी गंगा स्नान, शुक्रताल दर्शन; जयपुर के लिए प्रस्थान।" },
      { dayEn: "Day 14", dayHi: "दिन 14", titleEn: "Arrival Jaipur", titleHi: "जयपुर आगमन", descEn: "13 May: Arrival back in Jaipur. Yatra mangal.", descHi: "13 मई: जयपुर आगमन। यात्रा मंगल।" },
    ],
    includes: [
      { en: "AC 27-seater bus from Jaipur for full tour", hi: "पूरी यात्रा के लिए जयपुर से एसी 27 सीटर बस" },
      { en: "AC rooms in Haridwar; non-AC rooms at other stops", hi: "हरिद्वार में एसी कमरे; अन्य स्थानों पर नॉन-एसी कमरे" },
      { en: "Lunch and dinner included (satvik, no onion/garlic)", hi: "लंच और डिनर शामिल (सात्विक, बिना प्याज-लहसुन)" },
      { en: "Kedarnath hill stay with dinner included", hi: "केदारनाथ पहाड़ी ठहराव व डिनर शामिल" },
      { en: "Two-night stay in Badrinath", hi: "बद्रीनाथ में दो रात ठहराव" },
      { en: "Darshan coordination: Shukratal, Lakshagrah, Shiv Gufa, Yamunotri, Gangotri, Kedarnath, Badrinath", hi: "दर्शन समन्वय: शुक्रताल, लाक्षागृह, शिव गुफा, यमुनोत्री, गंगोत्री, केदारनाथ, बद्रीनाथ" },
    ],
    excludes: [
      { en: "Helicopter, horse, palki, taxi, auto charges", hi: "हेलीकॉप्टर, घोड़ा, पालकी, टैक्सी, ऑटो शुल्क" },
      { en: "Coffee, cold drinks, and personal expenses", hi: "कॉफी, कोल्ड ड्रिंक और व्यक्तिगत खर्च" },
      { en: "Special puja or services beyond itinerary", hi: "विशेष पूजा या यात्रा से बाहर की सेवाएं" },
      { en: "Travel/medical insurance", hi: "यात्रा/चिकित्सा बीमा" },
    ],
  },
  {
    id: "vrindavan-mathura",
    nameEn: "Vrindavan-Mathura Tour",
    nameHi: "वृंदावन-मथुरा दर्शन",
    descEn: "Visit the divine land of Lord Krishna - Vrindavan and Mathura. Experience the enchanting temples, ghats, and the spiritual essence of Braj Bhoomi where Lord Krishna spent his childhood.",
    descHi: "भगवान कृष्ण की दिव्य भूमि - वृंदावन और मथुरा के दर्शन करें। ब्रज भूमि के मनमोहक मंदिरों, घाटों और आध्यात्मिक सार का अनुभव करें जहां भगवान कृष्ण ने अपना बचपन बिताया।",
    duration: "4 Days / 3 Nights",
    durationHi: "4 दिन / 3 रातें",
    price: "₹8,999",
    datesEn: "Dates to be Announced",
    datesHi: "तारीखें घोषित की जाएंगी",
    image: IMAGES.vrindavan,
    highlights: [
      { en: "Banke Bihari Temple darshan", hi: "बांके बिहारी मंदिर दर्शन" },
      { en: "Krishna Janmabhoomi visit", hi: "कृष्ण जन्मभूमि दर्शन" },
      { en: "Govardhan Parikrama", hi: "गोवर्धन परिक्रमा" },
      { en: "Yamuna Aarti at Keshi Ghat", hi: "केशी घाट पर यमुना आरती" },
      { en: "ISKCON Temple visit", hi: "इस्कॉन मंदिर दर्शन" },
    ],
    itinerary: [
      { dayEn: "Day 1", dayHi: "दिन 1", titleEn: "Arrival in Mathura", titleHi: "मथुरा आगमन", descEn: "Arrive Mathura. Visit Krishna Janmabhoomi temple, Dwarkadhish temple, and Vishram Ghat. Evening Yamuna Aarti.", descHi: "मथुरा पहुंचें। कृष्ण जन्मभूमि मंदिर, द्वारकाधीश मंदिर और विश्राम घाट के दर्शन। शाम को यमुना आरती।" },
      { dayEn: "Day 2", dayHi: "दिन 2", titleEn: "Vrindavan Temples", titleHi: "वृंदावन मंदिर दर्शन", descEn: "Full day in Vrindavan. Visit Banke Bihari, Radha Raman, ISKCON, Prem Mandir, Nidhivan, and Rangji temple.", descHi: "वृंदावन में पूरा दिन। बांके बिहारी, राधा रमण, इस्कॉन, प्रेम मंदिर, निधिवन और रंगजी मंदिर के दर्शन।" },
      { dayEn: "Day 3", dayHi: "दिन 3", titleEn: "Govardhan & Barsana", titleHi: "गोवर्धन और बरसाना", descEn: "Visit Govardhan Hill for parikrama. Visit Barsana - birthplace of Radha Rani. Ladli Ji temple darshan.", descHi: "गोवर्धन पर्वत की परिक्रमा। बरसाना - राधा रानी का जन्मस्थान। लाडली जी मंदिर दर्शन।" },
      { dayEn: "Day 4", dayHi: "दिन 4", titleEn: "Departure", titleHi: "वापसी", descEn: "Morning visit to Galteshwar Mahadev and Kusum Sarovar. Departure with blessed memories.", descHi: "सुबह गल्तेश्वर महादेव और कुसुम सरोवर के दर्शन। पवित्र यादों के साथ वापसी।" },
    ],
    includes: [
      { en: "AC transport from Delhi", hi: "दिल्ली से एसी परिवहन" },
      { en: "3-star hotel accommodation", hi: "3-स्टार होटल में ठहरना" },
      { en: "Breakfast and dinner", hi: "नाश्ता और रात का खाना" },
      { en: "All temple visits with guide", hi: "गाइड के साथ सभी मंदिर दर्शन" },
      { en: "Govardhan Parikrama arrangements", hi: "गोवर्धन परिक्रमा की व्यवस्था" },
    ],
    excludes: [
      { en: "Personal expenses & donations", hi: "व्यक्तिगत खर्च और दान" },
      { en: "Lunch", hi: "दोपहर का भोजन" },
      { en: "Special puja charges", hi: "विशेष पूजा शुल्क" },
    ],
  },
  {
    id: "kashi-vishwanath",
    nameEn: "Kashi Vishwanath Yatra",
    nameHi: "काशी विश्वनाथ यात्रा",
    descEn: "Visit the ancient city of Varanasi - the spiritual capital of India. Experience the divine Ganga Aarti, visit Kashi Vishwanath Jyotirlinga, and explore the timeless ghats along the sacred Ganges.",
    descHi: "वाराणसी के प्राचीन शहर - भारत की आध्यात्मिक राजधानी के दर्शन करें। दिव्य गंगा आरती का अनुभव करें, काशी विश्वनाथ ज्योतिर्लिंग के दर्शन करें और पवित्र गंगा के किनारे शाश्वत घाटों का अन्वेषण करें।",
    duration: "5 Days / 4 Nights",
    durationHi: "5 दिन / 4 रातें",
    price: "₹12,999",
    datesEn: "Dates to be Announced",
    datesHi: "तारीखें घोषित की जाएंगी",
    image: IMAGES.varanasi,
    highlights: [
      { en: "Kashi Vishwanath Jyotirlinga darshan", hi: "काशी विश्वनाथ ज्योतिर्लिंग दर्शन" },
      { en: "Ganga Aarti at Dashashwamedh Ghat", hi: "दशाश्वमेध घाट पर गंगा आरती" },
      { en: "Boat ride on the Ganges at sunrise", hi: "सूर्योदय पर गंगा नौका विहार" },
      { en: "Sarnath Buddhist site visit", hi: "सारनाथ बौद्ध स्थल दर्शन" },
      { en: "Prayagraj Sangam visit", hi: "प्रयागराज संगम दर्शन" },
    ],
    itinerary: [
      { dayEn: "Day 1", dayHi: "दिन 1", titleEn: "Arrival in Varanasi", titleHi: "वाराणसी आगमन", descEn: "Arrive Varanasi. Check-in hotel. Evening Ganga Aarti at Dashashwamedh Ghat - a mesmerizing ceremony with thousands of diyas.", descHi: "वाराणसी पहुंचें। होटल चेक-इन। शाम को दशाश्वमेध घाट पर गंगा आरती - हजारों दीयों के साथ मनमोहक समारोह।" },
      { dayEn: "Day 2", dayHi: "दिन 2", titleEn: "Varanasi Temple Tour", titleHi: "वाराणसी मंदिर दर्शन", descEn: "Early morning boat ride. Visit Kashi Vishwanath temple, Annapurna temple, Sankat Mochan Hanuman temple, Tulsi Manas temple, and BHU.", descHi: "सुबह जल्दी नौका विहार। काशी विश्वनाथ मंदिर, अन्नपूर्णा मंदिर, संकट मोचन हनुमान मंदिर, तुलसी मानस मंदिर और BHU दर्शन।" },
      { dayEn: "Day 3", dayHi: "दिन 3", titleEn: "Sarnath Excursion", titleHi: "सारनाथ भ्रमण", descEn: "Visit Sarnath where Lord Buddha gave his first sermon. See Ashoka Pillar, Dhamek Stupa, and Sarnath Museum.", descHi: "सारनाथ के दर्शन जहां भगवान बुद्ध ने अपना पहला उपदेश दिया। अशोक स्तंभ, धमेक स्तूप और सारनाथ संग्रहालय देखें।" },
      { dayEn: "Day 4", dayHi: "दिन 4", titleEn: "Prayagraj Visit", titleHi: "प्रयागराज दर्शन", descEn: "Day trip to Prayagraj. Visit Triveni Sangam (confluence of Ganga, Yamuna, Saraswati). Holy dip and boat ride at Sangam.", descHi: "प्रयागराज का दिन भ्रमण। त्रिवेणी संगम (गंगा, यमुना, सरस्वती का संगम) दर्शन। संगम पर पवित्र स्नान और नौका विहार।" },
      { dayEn: "Day 5", dayHi: "दिन 5", titleEn: "Departure", titleHi: "वापसी", descEn: "Morning free for shopping (Banarasi silk sarees). Departure with blessed memories.", descHi: "सुबह खरीदारी (बनारसी सिल्क साड़ियां) के लिए खाली। पवित्र यादों के साथ वापसी।" },
    ],
    includes: [
      { en: "Train/AC bus transport", hi: "ट्रेन/एसी बस परिवहन" },
      { en: "Hotel near Kashi Vishwanath", hi: "काशी विश्वनाथ के पास होटल" },
      { en: "All meals (breakfast & dinner)", hi: "सभी भोजन (नाश्ता और रात का खाना)" },
      { en: "Boat rides included", hi: "नौका विहार शामिल" },
      { en: "Expert local guide", hi: "अनुभवी स्थानीय गाइड" },
    ],
    excludes: [
      { en: "Special puja & donation", hi: "विशेष पूजा और दान" },
      { en: "Shopping expenses", hi: "खरीदारी का खर्च" },
      { en: "Personal expenses", hi: "व्यक्तिगत खर्च" },
    ],
  },
  {
    id: "dwarka-somnath",
    nameEn: "Dwarka-Somnath Tour",
    nameHi: "द्वारका-सोमनाथ यात्रा",
    descEn: "Explore the divine kingdom of Lord Krishna at Dwarka and the magnificent Somnath Jyotirlinga in Gujarat. This tour covers the western pilgrimage circuit including Nageshwar, Bet Dwarka, and the stunning coastal temples.",
    descHi: "गुजरात में भगवान कृष्ण के दिव्य राज्य द्वारका और भव्य सोमनाथ ज्योतिर्लिंग का अन्वेषण करें। इस यात्रा में नागेश्वर, बेट द्वारका और शानदार तटीय मंदिरों सहित पश्चिमी तीर्थ सर्किट शामिल है।",
    duration: "6 Days / 5 Nights",
    durationHi: "6 दिन / 5 रातें",
    price: "₹15,999",
    datesEn: "Dates to be Announced",
    datesHi: "तारीखें घोषित की जाएंगी",
    image: IMAGES.dwarka,
    highlights: [
      { en: "Dwarkadhish Temple darshan", hi: "द्वारकाधीश मंदिर दर्शन" },
      { en: "Somnath Jyotirlinga aarti", hi: "सोमनाथ ज्योतिर्लिंग आरती" },
      { en: "Nageshwar Jyotirlinga visit", hi: "नागेश्वर ज्योतिर्लिंग दर्शन" },
      { en: "Bet Dwarka boat ride", hi: "बेट द्वारका नौका विहार" },
      { en: "Sound & Light show at Somnath", hi: "सोमनाथ में ध्वनि और प्रकाश शो" },
    ],
    itinerary: [
      { dayEn: "Day 1", dayHi: "दिन 1", titleEn: "Arrival in Dwarka", titleHi: "द्वारका आगमन", descEn: "Arrive Dwarka. Visit Dwarkadhish temple for evening aarti. Witness the sunset at Dwarka beach.", descHi: "द्वारका पहुंचें। शाम की आरती के लिए द्वारकाधीश मंदिर दर्शन। द्वारका बीच पर सूर्यास्त देखें।" },
      { dayEn: "Day 2", dayHi: "दिन 2", titleEn: "Dwarka Exploration", titleHi: "द्वारका भ्रमण", descEn: "Morning darshan at Dwarkadhish. Visit Rukmini temple, Gomti Ghat, Sudama Setu. Afternoon trip to Nageshwar Jyotirlinga.", descHi: "सुबह द्वारकाधीश दर्शन। रुक्मिणी मंदिर, गोमती घाट, सुदामा सेतु दर्शन। दोपहर को नागेश्वर ज्योतिर्लिंग यात्रा।" },
      { dayEn: "Day 3", dayHi: "दिन 3", titleEn: "Bet Dwarka", titleHi: "बेट द्वारका", descEn: "Boat ride to Bet Dwarka island. Visit ancient Krishna temple and coral reefs area. Return and evening free.", descHi: "बेट द्वारका द्वीप तक नौका विहार। प्राचीन कृष्ण मंदिर और मूंगा चट्टान क्षेत्र दर्शन। वापसी और शाम को विश्राम।" },
      { dayEn: "Day 4-5", dayHi: "दिन 4-5", titleEn: "Somnath & Gir", titleHi: "सोमनाथ और गिर", descEn: "Drive to Somnath. Visit Somnath Jyotirlinga, attend the magnificent aarti and Sound & Light show. Optional Gir forest visit.", descHi: "सोमनाथ के लिए प्रस्थान। सोमनाथ ज्योतिर्लिंग दर्शन, भव्य आरती और ध्वनि-प्रकाश शो। वैकल्पिक गिर वन भ्रमण।" },
      { dayEn: "Day 6", dayHi: "दिन 6", titleEn: "Departure", titleHi: "वापसी", descEn: "Morning visit to Triveni Sangam at Somnath. Departure with sacred memories.", descHi: "सुबह सोमनाथ में त्रिवेणी संगम दर्शन। पवित्र यादों के साथ वापसी।" },
    ],
    includes: [
      { en: "AC transport throughout", hi: "पूरी यात्रा में एसी परिवहन" },
      { en: "Hotel stay with breakfast & dinner", hi: "नाश्ता और रात के खाने के साथ होटल" },
      { en: "Boat ride to Bet Dwarka", hi: "बेट द्वारका नौका विहार" },
      { en: "Temple guide", hi: "मंदिर गाइड" },
    ],
    excludes: [
      { en: "Flight/train tickets", hi: "फ्लाइट/ट्रेन टिकट" },
      { en: "Personal expenses", hi: "व्यक्तिगत खर्च" },
      { en: "Gir safari charges", hi: "गिर सफारी शुल्क" },
    ],
  },
  {
    id: "tirupati-balaji",
    nameEn: "Tirupati Balaji Darshan",
    nameHi: "तिरुपति बालाजी दर्शन",
    descEn: "Experience the divine darshan of Lord Venkateswara at Tirupati, one of the most visited sacred places in the world. This tour includes special VIP darshan, Padmavathi temple visit, and the sacred seven hills pilgrimage.",
    descHi: "दुनिया के सबसे अधिक दर्शन किए जाने वाले पवित्र स्थानों में से एक तिरुपति में भगवान वेंकटेश्वर के दिव्य दर्शन का अनुभव करें। इस यात्रा में विशेष VIP दर्शन, पद्मावती मंदिर दर्शन और पवित्र सप्तगिरि तीर्थयात्रा शामिल है।",
    duration: "3 Days / 2 Nights",
    durationHi: "3 दिन / 2 रातें",
    price: "₹9,999",
    datesEn: "Dates to be Announced",
    datesHi: "तारीखें घोषित की जाएंगी",
    image: IMAGES.tirupati,
    highlights: [
      { en: "VIP/Special darshan at Tirumala", hi: "तिरुमाला में VIP/विशेष दर्शन" },
      { en: "Padmavathi temple visit", hi: "पद्मावती मंदिर दर्शन" },
      { en: "Laddu prasadam arrangement", hi: "लड्डू प्रसादम की व्यवस्था" },
      { en: "Srivari Mettu walking trail", hi: "श्रीवारी मेट्टु पैदल यात्रा" },
      { en: "Kapileshwara temple visit", hi: "कपिलेश्वर मंदिर दर्शन" },
    ],
    itinerary: [
      { dayEn: "Day 1", dayHi: "दिन 1", titleEn: "Arrival in Tirupati", titleHi: "तिरुपति आगमन", descEn: "Arrive Tirupati. Visit Padmavathi temple and Govindaraja Swamy temple. Evening rest for early morning darshan.", descHi: "तिरुपति पहुंचें। पद्मावती मंदिर और गोविंदराजस्वामी मंदिर दर्शन। सुबह जल्दी दर्शन के लिए शाम को विश्राम।" },
      { dayEn: "Day 2", dayHi: "दिन 2", titleEn: "Tirumala Darshan", titleHi: "तिरुमाला दर्शन", descEn: "Early morning drive up to Tirumala. Special darshan of Lord Venkateswara. Visit Akasaganga, Papavinasam waterfall. Collect Laddu prasadam.", descHi: "सुबह जल्दी तिरुमाला की ओर प्रस्थान। भगवान वेंकटेश्वर के विशेष दर्शन। आकाशगंगा, पापविनाशम जलप्रपात दर्शन। लड्डू प्रसादम लें।" },
      { dayEn: "Day 3", dayHi: "दिन 3", titleEn: "Departure", titleHi: "वापसी", descEn: "Visit Kapileshwara temple and Srinivasa Mangapuram. Departure with divine blessings of Lord Balaji.", descHi: "कपिलेश्वर मंदिर और श्रीनिवास मंगापुरम दर्शन। भगवान बालाजी के दिव्य आशीर्वाद के साथ वापसी।" },
    ],
    includes: [
      { en: "AC transport", hi: "एसी परिवहन" },
      { en: "Hotel near Tirumala", hi: "तिरुमाला के पास होटल" },
      { en: "Special darshan tickets", hi: "विशेष दर्शन टिकट" },
      { en: "Breakfast and dinner", hi: "नाश्ता और रात का खाना" },
      { en: "2 Laddu prasadam per person", hi: "प्रति व्यक्ति 2 लड्डू प्रसादम" },
    ],
    excludes: [
      { en: "Flight/train fare", hi: "फ्लाइट/ट्रेन किराया" },
      { en: "Donation at temple", hi: "मंदिर में दान" },
      { en: "Personal expenses", hi: "व्यक्तिगत खर्च" },
    ],
  },
  {
    id: "amarnath",
    nameEn: "Amarnath Yatra",
    nameHi: "अमरनाथ यात्रा",
    descEn: "Undertake the sacred Amarnath Yatra to the holy ice Shivalinga in the Himalayan cave at 3,888 meters. This challenging yet spiritually rewarding pilgrimage takes you through stunning Himalayan landscapes to one of Hinduism's holiest shrines.",
    descHi: "3,888 मीटर की ऊंचाई पर हिमालय की गुफा में पवित्र बर्फ के शिवलिंग की पवित्र अमरनाथ यात्रा करें। यह चुनौतीपूर्ण लेकिन आध्यात्मिक रूप से लाभदायक तीर्थयात्रा आपको हिंदू धर्म के सबसे पवित्र मंदिरों में से एक तक ले जाती है।",
    duration: "7 Days / 6 Nights",
    durationHi: "7 दिन / 6 रातें",
    price: "₹22,999",
    datesEn: "Dates to be Announced",
    datesHi: "तारीखें घोषित की जाएंगी",
    image: IMAGES.himalaya,
    highlights: [
      { en: "Holy cave darshan of ice Shivalinga", hi: "बर्फ के शिवलिंग के पवित्र गुफा दर्शन" },
      { en: "Pahalgam/Baltal route options", hi: "पहलगाम/बालटाल मार्ग विकल्प" },
      { en: "Helicopter service available", hi: "हेलीकॉप्टर सेवा उपलब्ध" },
      { en: "Medical support throughout trek", hi: "पूरे ट्रेक में चिकित्सा सहायता" },
      { en: "Stunning Kashmir valley views", hi: "कश्मीर घाटी के शानदार दृश्य" },
    ],
    itinerary: [
      { dayEn: "Day 1", dayHi: "दिन 1", titleEn: "Delhi to Srinagar", titleHi: "दिल्ली से श्रीनगर", descEn: "Fly to Srinagar. Transfer to hotel near Dal Lake. Evening Shikara ride and acclimatization.", descHi: "श्रीनगर फ्लाइट। डल लेक के पास होटल में चेक-इन। शाम को शिकारा राइड और अनुकूलन।" },
      { dayEn: "Day 2", dayHi: "दिन 2", titleEn: "Srinagar to Pahalgam", titleHi: "श्रीनगर से पहलगाम", descEn: "Drive to Pahalgam through scenic Kashmir valley. Visit Anantnag and Betaab Valley en route. Registration and medical check-up.", descHi: "सुंदर कश्मीर घाटी के माध्यम से पहलगाम तक ड्राइव। रास्ते में अनंतनाग और बेताब वैली दर्शन। पंजीकरण और मेडिकल चेक-अप।" },
      { dayEn: "Day 3", dayHi: "दिन 3", titleEn: "Pahalgam to Sheshnag", titleHi: "पहलगाम से शेषनाग", descEn: "Begin trek from Chandanwari (16 km). Pass through Pissu Top. Camp at beautiful Sheshnag Lake.", descHi: "चंदनवाड़ी से ट्रेक शुरू (16 किमी)। पिस्सू टॉप से गुजरें। खूबसूरत शेषनाग झील पर कैम्प।" },
      { dayEn: "Day 4", dayHi: "दिन 4", titleEn: "Sheshnag to Panchtarni", titleHi: "शेषनाग से पंचतरणी", descEn: "Trek from Sheshnag to Panchtarni via Mahagunas Top (14,500 ft). Camp at Panchtarni.", descHi: "शेषनाग से महागुणस टॉप (14,500 फीट) होते हुए पंचतरणी तक ट्रेक। पंचतरणी पर कैम्प।" },
      { dayEn: "Day 5", dayHi: "दिन 5", titleEn: "Holy Cave Darshan", titleHi: "पवित्र गुफा दर्शन", descEn: "Early morning trek to Amarnath Holy Cave (6 km). Darshan of the sacred ice Shivalinga. Return to Panchtarni.", descHi: "सुबह जल्दी अमरनाथ पवित्र गुफा तक ट्रेक (6 किमी)। पवित्र बर्फ के शिवलिंग के दर्शन। पंचतरणी वापसी।" },
      { dayEn: "Day 6", dayHi: "दिन 6", titleEn: "Return Trek", titleHi: "वापसी ट्रेक", descEn: "Trek back to Pahalgam. Rest and celebrate the completion of the sacred yatra.", descHi: "पहलगाम तक वापसी ट्रेक। विश्राम और पवित्र यात्रा की सफलता का जश्न।" },
      { dayEn: "Day 7", dayHi: "दिन 7", titleEn: "Return to Delhi", titleHi: "दिल्ली वापसी", descEn: "Drive to Srinagar. Fly back to Delhi. Tour ends.", descHi: "श्रीनगर तक ड्राइव। दिल्ली वापसी फ्लाइट। यात्रा समाप्त।" },
    ],
    includes: [
      { en: "Flights (Delhi-Srinagar-Delhi)", hi: "फ्लाइट (दिल्ली-श्रीनगर-दिल्ली)" },
      { en: "All accommodation & camping", hi: "सभी आवास और कैम्पिंग" },
      { en: "All meals during trek", hi: "ट्रेक के दौरान सभी भोजन" },
      { en: "Pony/Porter support", hi: "घोड़ा/कुली सहायता" },
      { en: "Medical kit & oxygen", hi: "मेडिकल किट और ऑक्सीजन" },
      { en: "Registration & permits", hi: "पंजीकरण और परमिट" },
    ],
    excludes: [
      { en: "Helicopter charges", hi: "हेलीकॉप्टर शुल्क" },
      { en: "Personal trekking gear", hi: "व्यक्तिगत ट्रेकिंग गियर" },
      { en: "Tips and gratitudes", hi: "टिप्स और आभार" },
      { en: "Travel insurance", hi: "यात्रा बीमा" },
    ],
  },
];

export const youtubeVideos = [
  { id: "v1", title: { en: "Char Dham Yatra Complete Guide", hi: "चार धाम यात्रा पूर्ण गाइड" }, videoId: "MZc5aXVHK-s", category: { en: "Char Dham", hi: "चार धाम" } },
  { id: "v2", title: { en: "Varanasi Ganga Aarti Full Video", hi: "वाराणसी गंगा आरती पूर्ण वीडियो" }, videoId: "6ate2Q7Tq2g", category: { en: "Varanasi", hi: "वाराणसी" } },
  { id: "v3", title: { en: "Vrindavan Temples Tour", hi: "वृंदावन मंदिर भ्रमण" }, videoId: "yP30A_PnY9Q", category: { en: "Vrindavan", hi: "वृंदावन" } },
  { id: "v4", title: { en: "Kedarnath Temple Documentary", hi: "केदारनाथ मंदिर वृत्तचित्र" }, videoId: "w7F8UrteTtI", category: { en: "Char Dham", hi: "चार धाम" } },
  { id: "v5", title: { en: "Tirupati Balaji Darshan Guide", hi: "तिरुपति बालाजी दर्शन गाइड" }, videoId: "fftQp57nGns", category: { en: "Tirupati", hi: "तिरुपति" } },
  { id: "v6", title: { en: "Amarnath Yatra Experience", hi: "अमरनाथ यात्रा अनुभव" }, videoId: "iXBuRoT8REA", category: { en: "Amarnath", hi: "अमरनाथ" } },
  { id: "v7", title: { en: "Dwarka Somnath Complete Tour", hi: "द्वारका सोमनाथ पूर्ण यात्रा" }, videoId: "nDNUhkclvww", category: { en: "Dwarka", hi: "द्वारका" } },
  { id: "v8", title: { en: "Spiritual India Journey", hi: "आध्यात्मिक भारत यात्रा" }, videoId: "a5IzcMoKy64", category: { en: "Spiritual", hi: "आध्यात्मिक" } },
];

export const testimonials = [
  {
    id: 1,
    nameEn: "Rajesh Kumar",
    nameHi: "राजेश कुमार",
    locationEn: "Delhi",
    locationHi: "दिल्ली",
    textEn: "The Char Dham Yatra was perfectly organized. Every detail was taken care of. The guides were knowledgeable and the spiritual experience was unforgettable. Highly recommended!",
    textHi: "चार धाम यात्रा पूरी तरह से व्यवस्थित थी। हर विवरण का ध्यान रखा गया। गाइड जानकार थे और आध्यात्मिक अनुभव अविस्मरणीय था। अत्यधिक अनुशंसित!",
    rating: 5,
  },
  {
    id: 2,
    nameEn: "Sunita Sharma",
    nameHi: "सुनीता शर्मा",
    locationEn: "Jaipur",
    locationHi: "जयपुर",
    textEn: "Vrindavan-Mathura tour was divine. The team arranged special pujas and the accommodation was excellent. Will definitely travel with them again.",
    textHi: "वृंदावन-मथुरा यात्रा दिव्य थी। टीम ने विशेष पूजाओं की व्यवस्था की और आवास उत्कृष्ट था। निश्चित रूप से उनके साथ फिर से यात्रा करूंगी।",
    rating: 5,
  },
  {
    id: 3,
    nameEn: "Amit Patel",
    nameHi: "अमित पटेल",
    locationEn: "Ahmedabad",
    locationHi: "अहमदाबाद",
    textEn: "Dwarka-Somnath tour was well planned. The Somnath aarti was the highlight. Professional service and great value for money.",
    textHi: "द्वारका-सोमनाथ यात्रा अच्छी तरह से नियोजित थी। सोमनाथ आरती मुख्य आकर्षण थी। पेशेवर सेवा और पैसे का बढ़िया मूल्य।",
    rating: 4,
  },
];
